# Project information
site_name: 蟒营™时间管理(0TM)原型班
copyright: 蟒营™101camp

# Repository
repo_name: 101camp/tm
repo_url: https://github.com/101camp/tm
# edit_uri: ""

# Configuration
theme:
#  name: null
#  custom_dir: mkdocs_alabaster
  name: material
  custom_dir: custom_material

  language: zh
  feature:
    # tabs: true
  #palette:
  #  primary: indigo
  #  accent: indigo

# Plugins
plugins:
  - search

# Page tree
nav:
  - 首页: index.md
  - 概览: /1overview/
  - 进展: /2record/
  - 成果: /3work/
  - 经验: /4experience/
  - 关于:
    - Powered by: poweredby.md 
    - License: license.md

extra_css:
  - 'stylesheets/extra.css'
